<template>
    <div class="container mx-auto p-4">
        <div class="text-5xl mb-4">Is this a place?</div>
        <div>
            <button v-for="(country, key) in country_data"
                    class="bg-gray-200 border-gray-400 py-2 px-4 rounded border-4 m-1 focus:outline-none"
                    @click="() => select_country(key)">
                {{country.name}} <img :src="`static/${key}-flag.png`" width="32px" height="19px" class="inline ml-2" />
            </button>
        </div>
        <div>
            <p class="my-2">Here is a list of places in {{selected_country.name}}. Only some of them are real, and some have been auto-generated by a neural network!</p>
            <p class="my-2">See if you can work out which places are real and which are fake...</p>
        </div>
        <div class="container mx-auto p-4">
            <div v-for="word in words">
                <button class="bg-info py-2 px-4 border-gray-400 border-4 m-1 rounded focus:outline-none"
                        v-bind:class="{'bg-yellow-200' : word.selected === 'fake', 'bg-teal-200': word.selected === 'real'}"
                        @click="() => click_word(word)" :disabled="check_answers">
                    {{word.word}}
                    <span v-if="word.selected === 'fake'">(fake)</span>
                    <span v-if="word.selected === 'real'">(real)</span>
                </button>
                <span v-if="check_answers">
                    <template v-if="word.selected === word.status">
                        <span v-if="word.status === 'real'">
<!--                            <span class="bg-green-300 py-2 px-4 rounded">✔️Correct!</span>-->
                            ✔️ {{word.word}} is a <a target="_blank" :href="`https://www.google.com/search?q=${word.word}`" class="underline">real pace in {{selected_country.name}}</a>.
                        </span>
                        <span v-else>
<!--                            <span class="bg-green-300 py-2 px-4 rounded">Correct!</span>-->
                            ✔️ {{word.word}} is a fake place, generated by the neural network.
                        </span>
                    </template>
                    <template v-else>
                        <span v-if="word.status === 'real'">
<!--                            <span class="bg-red-300 py-2 px-4 rounded">Incorrect!</span>-->
                            ❌  {{word.word}} is actually a <a target="_blank" :href="`https://www.google.com/search?q=${word.word}`" class="underline">real pace in {{selected_country.name}}</a>.
                        </span>
                        <span v-else>
<!--                            <span class="bg-red-300 py-2 px-4 rounded">Incorrect!</span>-->
                            ❌  {{word.word}} is actually a fake place, generated by the neural network.
                        </span>
                    </template>
                </span>
            </div>
        </div>
        <div class="my-2">
            <button class="bg-blue-500 text-white font-bold py-2 px-4 rounded focus:outline-none"
                    :class="{'opacity-50 cursor-not-allowed': !all_words_decided, 'hover:bg-blue-700': all_words_decided}"
                    @click="click_check_answers" :disabled="!all_words_decided">
                Check answers
            </button>
        </div>
        <div class="my-2">
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 mt-4 rounded focus:outline-none" @click="click_new_words">
                Play another round
            </button>
        </div>
    </div>
</template>

<script>

module.exports = {
    data: function() {
        return {
            words: [],
            check_answers: false,
            selected_country_key: 'england',
            country_data: {
                'england': {
                    name: 'England',
                    rnn_name: 'rnn_english_places',
                    real_name: 'real_english_places',
                    rnn_iteration_number: 12_600_000,
                },
                'scotland': {
                    name: 'Scotland',
                    rnn_name: 'rnn_scottish_places',
                    real_name: 'real_scottish_places',
                    rnn_iteration_number: 15_900_000,
                },
                'wales': {
                    name: 'Wales',
                    rnn_name: 'rnn_welsh_places',
                    real_name: 'real_welsh_places',
                    rnn_iteration_number: 15_900_000,
                },
                'ireland': {
                    name: 'Ireland',
                    rnn_name: 'rnn_irish_places',
                    real_name: 'real_irish_places',
                    rnn_iteration_number: 14_800_000,
                },
                'france': {
                    name: 'France',
                    rnn_name: 'rnn_french_places',
                    real_name: 'real_french_places',
                    rnn_iteration_number: 14_200_000,
                },
            },
        }
    },
    computed: {
        selected_country: function() {
            return this.country_data[this.selected_country_key]
        },

        all_words_decided: function() {
            return this.words.every((word) => word.selected !== '')
        }
    },
    methods: {
        select_country: function(key) {
            this.selected_country_key = key
            this.get_new_words()
        },

        click_word: function(word) {
            if (word.selected === 'fake') {
                word.selected = 'real'
            }
            else {
                word.selected = 'fake'
            }
        },

        click_check_answers: function() {
            this.check_answers = true
        },

        click_new_words: function() {
            this.check_answers = false
            this.get_new_words()
        },

        get_new_words: function() {
            this.check_answers = false

            // Use API
            // this.get_words_from_api((words) => {
            //     this.words = words
            // })

            // Use word list
            this.words = this.get_words_from_file()
        },

        get_words_from_api: function(callback) {
            const num_fake_words = getRandom([2, 3, 4], 1)
            const num_real_words = 6 - num_fake_words
            const words = []
            axios.get(`/api/v1/fake_words/?save_folder=${this.selected_country.rnn_name}&iteration_number=${this.selected_country.rnn_iteration_number}&num_words=${num_fake_words}`)
                .then((response) => {
                    if (response.data.status !== 'Success') {
                        console.error(response.data.error_message)
                    }

                    words.push(...response.data.fake_words.map((word) => { return {
                        word: word,
                        status: 'fake',
                        selected: '',
                    }}))

                    axios.get(`/api/v1/real_words/?save_folder=${this.selected_country.rnn_name}&num_words=${num_real_words}`)
                        .then((response) => {
                            if (response.data.status !== 'Success') {
                                console.error(response.data.error_message)
                            }

                            words.push(...response.data.real_words.map((word) => { return {
                                word: word,
                                status: 'real',
                                selected: '',
                            }}))
                            shuffle(words)

                            callback(words)
                        })
                        .catch((error) => {
                            console.error(error)
                        });
                })
                .catch((error) => {
                    console.error(error)
                });
        },

        get_words_from_file: function() {
            const fake_names = window[this.selected_country.rnn_name]
            const real_names = window[this.selected_country.real_name]
            const num_fake_words = getRandom([2, 3, 4], 1)
            const num_real_words = 6 - num_fake_words
            const words = []
            words.push(...getRandom(fake_names, num_fake_words).map((word) => { return {
                word: word,
                status: 'fake',
                selected: '',
            }}))
            words.push(...getRandom(real_names, num_real_words).map((word) => { return {
                word: word,
                status: 'real',
                selected: '',
            }}))
            shuffle(words)
            return(words)
        },
    },
    mounted: function() {
        this.get_new_words()
    },
}

/**
 * Fisher-Yates Shuffle, from https://stackoverflow.com/a/2450976/598749
 * Shuffles an array in-place.
 */
function shuffle(array) {
  var currentIndex = array.length, temporaryValue, randomIndex;

  // While there remain elements to shuffle...
  while (0 !== currentIndex) {

    // Pick a remaining element...
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex -= 1;

    // And swap it with the current element.
    temporaryValue = array[currentIndex];
    array[currentIndex] = array[randomIndex];
    array[randomIndex] = temporaryValue;
  }

  return array;
}

/**
 * Randomly sample from an array without replacement, from https://stackoverflow.com/a/19270021/598749
 */
function getRandom(arr, n) {
    var result = new Array(n),
        len = arr.length,
        taken = new Array(len);
    if (n > len)
        throw new RangeError("getRandom: more elements taken than available");
    while (n--) {
        var x = Math.floor(Math.random() * len);
        result[n] = arr[x in taken ? taken[x] : x];
        taken[x] = --len in taken ? taken[len] : len;
    }
    return result;
}
</script>

<style>

</style>