<template>
    <div class="container mx-auto p-4">
        <div class="text-5xl mb-4">Is this a place?</div>
        <div>
            <p class="my-2">Here is a list of places in England. Only some of them are real, and some have been auto-generated by a neural network!</p>
            <p class="my-2">See if you can work out which places are real and which are fake...</p>
        </div>
        <div class="container mx-auto p-4">
            <div v-for="word in words">
                <button class="bg-info py-2 px-4 border-solid border-4 m-1 rounded focus:outline-none" @click="() => click_word(word)" :disabled="check_answers">
                    {{word.word}}
                </button>
                <button v-if="word.selected === 'fake'" class="bg-yellow-300 py-2 px-4 rounded focus:outline-none" @click="() => click_word(word)" :disabled="check_answers">fake</button>
                <button v-if="word.selected === 'real'" class="bg-teal-300 py-2 px-4 rounded focus:outline-none" @click="() => click_word(word)" :disabled="check_answers">real</button>
                <span v-if="check_answers">
                    <template v-if="word.selected === word.status">
                        <span v-if="word.status === 'real'">
                            <span class="bg-green-300 py-2 px-4 rounded">Correct!</span>
                            {{word.word}} is a <a target="_blank" :href="`https://en.wikipedia.org/wiki/${word.word}`" class="underline">real pace in England</a>.
                        </span>
                        <span v-else>
                            <span class="bg-green-300 py-2 px-4 rounded">Correct!</span>
                            {{word.word}} is a fake place, generated by the neural network.
                        </span>
                    </template>
                    <template v-else>
                        <span v-if="word.status === 'real'">
                            <span class="bg-red-300 py-2 px-4 rounded">Incorrect!</span>
                            {{word.word}} is actually a <a target="_blank" :href="`https://en.wikipedia.org/wiki/${word.word}`" class="underline">real pace in England</a>.
                        </span>
                        <span v-else>
                            <span class="bg-red-300 py-2 px-4 rounded">Incorrect!</span>
                            {{word.word}} is actually a fake place, generated by the neural network.
                        </span>
                    </template>
                </span>
            </div>
        </div>
        <div class="my-2">
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none" @click="click_check_answers">
                Check answers
            </button>
        </div>
        <div class="my-2">
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none" @click="click_new_words">
                Play another round
            </button>
        </div>
    </div>
</template>

<script>
module.exports = {
    data: function() {
        return {
            words: [],
            check_answers: false,
        }
    },
    methods: {
        click_word: function(word) {
            if (word.selected === 'fake') {
                word.selected = 'real'
            }
            else {
                word.selected = 'fake'
            }
        },

        click_check_answers: function() {
            this.check_answers = true
        },

        click_new_words: function() {
            this.check_answers = false
            this.get_new_words()
        },

        get_new_words: function() {
            var words = []
            axios.get('/api/v1/fake_words/?save_folder=15_very_long_training&iteration_number=12_600_000&num_words=3')
                .then((response) => {
                    if (response.data.status !== 'Success') {
                        console.error(response.data.error_message)
                    }

                    words.push(...response.data.fake_words.map((word) => { return {
                        word: word,
                        status: 'fake',
                        selected: 'real',
                    }}))

                    axios.get('/api/v1/real_words/?save_folder=15_very_long_training&num_words=3')
                        .then((response) => {
                            if (response.data.status !== 'Success') {
                                console.error(response.data.error_message)
                            }

                            words.push(...response.data.real_words.map((word) => { return {
                                word: word,
                                status: 'real',
                                selected: 'real',
                            }}))
                            shuffle(words)

                            this.words = words
                        })
                        .catch((error) => {
                            console.error(error)
                        });
                })
                .catch((error) => {
                    console.error(error)
                });
        },
    },
    mounted: function() {
        this.get_new_words()
    },
}

/**
 * Fisher-Yates Shuffle, from https://stackoverflow.com/a/2450976/598749
 * Shuffles an array in-place.
 */
function shuffle(array) {
  var currentIndex = array.length, temporaryValue, randomIndex;

  // While there remain elements to shuffle...
  while (0 !== currentIndex) {

    // Pick a remaining element...
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex -= 1;

    // And swap it with the current element.
    temporaryValue = array[currentIndex];
    array[currentIndex] = array[randomIndex];
    array[randomIndex] = temporaryValue;
  }

  return array;
}
</script>

<style>

</style>