<template>
    <div class="container mx-auto p-4">
        <div class="text-5xl mb-4">Is this a place?</div>
        <div>
            <p class="my-2">Here is a list of places in England. Only some of them are real, and some have been auto-generated by a neural network!</p>
            <p class="my-2">See if you can work out which places are real and which are fake...</p>
        </div>
        <div class="container mx-auto p-4">
            <div v-for="word in words">
                <button class="bg-info py-2 px-4 border-solid border-4 m-1 rounded focus:outline-none" @click="() => click_word(word)" :disabled="check_answers">
                    {{word.word}}
                </button>
                <button v-if="word.selected === 'fake'" class="bg-yellow-300 py-2 px-4 rounded focus:outline-none" @click="() => click_word(word)" :disabled="check_answers">fake</button>
                <button v-if="word.selected === 'real'" class="bg-teal-300 py-2 px-4 rounded focus:outline-none" @click="() => click_word(word)" :disabled="check_answers">real</button>
                <span v-if="check_answers">
                    <template v-if="word.selected === word.status">
                        <span v-if="word.status === 'real'">
                            <span class="bg-green-300 py-2 px-4 rounded">Correct!</span>
                            {{word.word}} is a <a target="_blank" :href="`https://www.google.com/search?q=${word.word}`" class="underline">real pace in England</a>.
                        </span>
                        <span v-else>
                            <span class="bg-green-300 py-2 px-4 rounded">Correct!</span>
                            {{word.word}} is a fake place, generated by the neural network.
                        </span>
                    </template>
                    <template v-else>
                        <span v-if="word.status === 'real'">
                            <span class="bg-red-300 py-2 px-4 rounded">Incorrect!</span>
                            {{word.word}} is actually a <a target="_blank" :href="`https://www.google.com/search?q=${word.word}`" class="underline">real pace in England</a>.
                        </span>
                        <span v-else>
                            <span class="bg-red-300 py-2 px-4 rounded">Incorrect!</span>
                            {{word.word}} is actually a fake place, generated by the neural network.
                        </span>
                    </template>
                </span>
            </div>
        </div>
        <div class="my-2">
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none" @click="click_check_answers">
                Check answers
            </button>
        </div>
        <div class="my-2">
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none" @click="click_new_words">
                Play another round
            </button>
        </div>
    </div>
</template>

<script>

module.exports = {
    data: function() {
        return {
            words: [],
            check_answers: false,
            rnn_name: 'rnn_english_places',
            real_name: 'real_english_places',
            rnn_iteration_number: 12_600_000,
        }
    },
    methods: {
        click_word: function(word) {
            if (word.selected === 'fake') {
                word.selected = 'real'
            }
            else {
                word.selected = 'fake'
            }
        },

        click_check_answers: function() {
            this.check_answers = true
        },

        click_new_words: function() {
            this.check_answers = false
            this.get_new_words()
        },

        get_new_words: function() {
            // Use API
            // this.get_words_from_api(3, (words) => {
            //     this.words = words
            // })

            // Use word list
            this.words = this.get_words_from_file(3)
        },

        get_words_from_api: function(num_words, callback) {
            const words = []
            axios.get(`/api/v1/fake_words/?save_folder=${this.rnn_name}&iteration_number=${this.rnn_iteration_number}&num_words=3`)
                .then((response) => {
                    if (response.data.status !== 'Success') {
                        console.error(response.data.error_message)
                    }

                    words.push(...response.data.fake_words.map((word) => { return {
                        word: word,
                        status: 'fake',
                        selected: 'real',
                    }}))

                    axios.get(`/api/v1/real_words/?save_folder=${this.rnn_name}&num_words=3`)
                        .then((response) => {
                            if (response.data.status !== 'Success') {
                                console.error(response.data.error_message)
                            }

                            words.push(...response.data.real_words.map((word) => { return {
                                word: word,
                                status: 'real',
                                selected: 'real',
                            }}))
                            shuffle(words)

                            callback(words)
                        })
                        .catch((error) => {
                            console.error(error)
                        });
                })
                .catch((error) => {
                    console.error(error)
                });
        },

        get_words_from_file: function(num_words) {
            const fake_names = window[this.rnn_name]
            const real_names = window[this.real_name]
            const words = []
            words.push(...getRandom(fake_names, num_words).map((word) => { return {
                word: word,
                status: 'fake',
                selected: 'real',
            }}))
            words.push(...getRandom(real_names, num_words).map((word) => { return {
                word: word,
                status: 'real',
                selected: 'real',
            }}))
            shuffle(words)
            return(words)
        },
    },
    mounted: function() {
        this.get_new_words()
    },
}

/**
 * Fisher-Yates Shuffle, from https://stackoverflow.com/a/2450976/598749
 * Shuffles an array in-place.
 */
function shuffle(array) {
  var currentIndex = array.length, temporaryValue, randomIndex;

  // While there remain elements to shuffle...
  while (0 !== currentIndex) {

    // Pick a remaining element...
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex -= 1;

    // And swap it with the current element.
    temporaryValue = array[currentIndex];
    array[currentIndex] = array[randomIndex];
    array[randomIndex] = temporaryValue;
  }

  return array;
}

/**
 * Randomly sample from an array without replacement, from https://stackoverflow.com/a/19270021/598749
 */
function getRandom(arr, n) {
    var result = new Array(n),
        len = arr.length,
        taken = new Array(len);
    if (n > len)
        throw new RangeError("getRandom: more elements taken than available");
    while (n--) {
        var x = Math.floor(Math.random() * len);
        result[n] = arr[x in taken ? taken[x] : x];
        taken[x] = --len in taken ? taken[len] : len;
    }
    return result;
}
</script>

<style>

</style>